name: CI

on: workflow_dispatch

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16]
        include:
          - os: windows-latest
            node_version: 14
      fail-fast: false
    name: "Test on node-${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Run CI tests
        run: npm run ci
